language: node_js
node_js:
  - "stable"

script:
  - npm run lint
  - npm run test:unit
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: dist
  on:
    branch: master