module.exports = {
  NEW_SPENDING: 'NEW_SPENDING',
  NEW_MONTHLY_LIMIT: 'NEW_MONTHLY_LIMIT',
  NEW_PAYCHECK_DAY: 'NEW_PAYCHECK_DAY',
  UPDATED_INPUT: 'UPDATED_INPUT',
  INPUT_SUBMITED: 'INPUT_SUBMITED',
};
